CREATE DATABASE STUDENT;

Create TABLE STUDENT.PUBLIC.School(
  id int AUTO_INCREMENT PRIMARY KEY ,
  name_school VARCHAR(100)
);

Create TABLE STUDENT.PUBLIC.Teacher(
  id int AUTO_INCREMENT PRIMARY KEY ,
  name_teacher VARCHAR(100),
  id_school int NOT NULL,
  FOREIGN KEY  (id_school) REFERENCES School(id)
);

Create TABLE STUDENT.PUBLIC.Student(
  id int AUTO_INCREMENT PRIMARY KEY ,
  name_student VARCHAR(100),
  id_school int NOT NULL,
  FOREIGN KEY  (id_school) REFERENCES School(id)
);

Create TABLE STUDENT.PUBLIC.Student_Teacher(
  id int AUTO_INCREMENT PRIMARY KEY ,
  id_student int not null,
  id_teacher int NOT NULL,
  FOREIGN KEY  (id_student) REFERENCES Student(id),
  FOREIGN KEY (id_teacher) REFERENCES Teacher(id)
);

INSERT into SCHOOL(NAME_SCHOOL) VALUES ('number 1');
INSERT into SCHOOL(NAME_SCHOOL) VALUES ('number 2');
INSERT into SCHOOL(NAME_SCHOOL) VALUES ('number 3');
INSERT into SCHOOL(NAME_SCHOOL) VALUES ('number 4');
INSERT into SCHOOL(NAME_SCHOOL) VALUES ('number 5');
INSERT into SCHOOL(NAME_SCHOOL) VALUES ('number 6');
INSERT into SCHOOL(NAME_SCHOOL) VALUES ('number 7');
INSERT into SCHOOL(NAME_SCHOOL) VALUES ('number 8');

INSERT into STUDENT(NAME_STUDENT,ID_SCHOOL) VALUES ('student 1',8);
INSERT into STUDENT(NAME_STUDENT,ID_SCHOOL) VALUES ('student 2',7);
INSERT into STUDENT(NAME_STUDENT,ID_SCHOOL) VALUES ('student 3',6);
INSERT into STUDENT(NAME_STUDENT,ID_SCHOOL) VALUES ('student 4',5);
INSERT into STUDENT(NAME_STUDENT,ID_SCHOOL) VALUES ('student 5',4);
INSERT into STUDENT(NAME_STUDENT,ID_SCHOOL) VALUES ('student 6',3);
INSERT into STUDENT(NAME_STUDENT,ID_SCHOOL) VALUES ('student 7',2);
INSERT into STUDENT(NAME_STUDENT,ID_SCHOOL) VALUES ('student 8',1);

INSERT into TEACHER(NAME_TEACHER,ID_SCHOOL) VALUES ('teacher 1',8);
INSERT into TEACHER(NAME_TEACHER,ID_SCHOOL) VALUES ('teacher 2',7);
INSERT into TEACHER(NAME_TEACHER,ID_SCHOOL) VALUES ('teacher 3',6);
INSERT into TEACHER(NAME_TEACHER,ID_SCHOOL) VALUES ('teacher 4',5);
INSERT into TEACHER(NAME_TEACHER,ID_SCHOOL) VALUES ('teacher 5',4);
INSERT into TEACHER(NAME_TEACHER,ID_SCHOOL) VALUES ('teacher 6',3);
INSERT into TEACHER(NAME_TEACHER,ID_SCHOOL) VALUES ('teacher 7',2);
INSERT into TEACHER(NAME_TEACHER,ID_SCHOOL) VALUES ('teacher 8',1);

INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (1,8);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (1,6);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (1,4);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (1,2);

INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (2,1);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (2,3);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (2,5);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (2,7);

INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (3,1);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (3,2);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (3,3);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (3,4);

INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (4,5);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (4,6);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (4,7);
INSERT into STUDENT_TEACHER(ID_TEACHER,ID_STUDENT) VALUES (4,8);